### ISSUE TITLE
LiveStream camera video flipped horizontally

### ISSUE THREAD

**Issue by steve-sun-me** [GetStream/stream-video-swift#348]
## What did you do?
Followed the tutorial and launched live stream view

## What did you expect to happen?
Front camera video has the right orientation as other live streaming apps

## What happened instead?
Front camera video flipped horizontally

## GetStream Environment
**GetStream Video version: 0.5.3**
**GetStream Video frameworks: StreamVideoSwiftUI** 
**iOS version: 17.2**
**Swift version: 5**
**Xcode version: 15.3**
**Device: iPhone 13**

## Additional context
I am not sure if this is expected, checked docs and code didn't see a way to adjust the orientation so started as a bug report but feel free to move it 🙏

**Comment by martinmitrevski** [comment]
Hey @steve-sun-me,

Thanks for creating the issue. The flipping is supported depending on which component you use. If you use the higher level one `VideoCallParticipantView`, this is automatically done, depending on whether the user is the current one.

If you use the `VideoRendererView`, which is a lower level component for displaying video tracks, you would need to apply the modifier by yourself:
```swift
.rotation3DEffect(.degrees(180), axis: (x: 0, y: 1, z: 0))
```
You can check whether the view is for the current user with the following code:
```swift
if participant.id == streamVideo.state.activeCall?.state.localParticipant?.id {
}
```
Hope that helps.

Let me know if you have additional questions.
Best, Martin

**Comment by steve-sun-me** [comment]
Hey @martinmitrevski, thanks for the update and appreciate the reply. We will try to do the same for Android as well. Is it possible to include this in the doc?

**Comment by martinmitrevski** [comment]
Thanks @steve-sun-me. Yes, we will update the docs accordingly: https://github.com/GetStream/stream-video-swift/pull/349. 

Best, Martin
