### ISSUE TITLE
i420->NV12 vs i420->ARGB

### ISSUE THREAD

**Issue by nathanwhy** [GetStream/stream-video-swift#398]
I just read the [Boost Performance by Over 100x Using the Accelerate Framework](https://getstream.io/blog/accelerate-framework/).
Actually `AVSampleBufferDisplayLayer` of PIP accepts two types of streams, RGBA and YUV-NV12.
Why not consider converting the stream directly to YUV-NV12? This might perform better than ARGB.

**Comment by ipavlidakis** [comment]
Hi @nathanwhy, do you have any resources that you can share about the support for YUV-NV12 on `AVSampleBufferDisplayLayer`?

**Comment by nathanwhy** [comment]
How about:
https://github.com/TelegramMessenger/tgcalls/blob/master/tgcalls/platform/darwin/VideoSampleBufferView.mm#L425

**Comment by testableapple** [comment]
Hi @nathanwhy,

Thanks for your suggestion. We might consider leveraging it in the future, but for now, we are happy with our current solution and don't plan to change it anytime soon.

Kind regards,
Alexey
