### ISSUE TITLE
VisionOS support possible in the future?

### ISSUE THREAD

**Issue by DavidCredo** [GetStream/stream-video-swift#441]
Really loving the SwiftUI API, great work! 
My current understanding is that the SDK doesn't work on visionOS, since the the platform isn't included in the XCFramework binaries.
Is there any chance that this might be possible in the future?
Still, thanks for providing such an awesome SDK!

**Comment by martinmitrevski** [comment]
Hi @DavidCredo,

Thanks for the kind words, we're glad you like our SDK 🙏 

About your question: there are no immediate plans for visionOS (i.e. in the next few months). Our long term plans definitely have visionOS in mind, we just need enough interest from customers and bigger adoption from users.

Closing the ticket for now, but eventually this should happen.

Best, Martin
