### ISSUE TITLE
Display camera feed without creating a call

### ISSUE THREAD

**Issue by andreasteich** [GetStream/stream-video-swift#489]
## What are you trying to achieve?
I want to display the camera feed without actually creating a call.

## If possible, how can you achieve this currently?
Maybe possible, but I can't find any information after several hours reading the docs.

## What would be the better way?
Update the docs if possible yet, otherwise would be a great feature to use!

**Comment by ipavlidakis** [comment]
Hey @andreasteich,

Thanks for reaching out. Do you mind elaborating more on your use case?

Best regards,
Ilias

**Comment by andreasteich** [comment]
No, definitely not. I'm trying to create an application using AVFoundation, the Vision framework for image analysis, and WebRTC. Since this is initially a prototype and the GetStream SDK seemed very flexible for these purposes, I decided to use GetStream. Now, I would like to achieve the following:

As soon as the user opens the application and is authenticated, I want to display the live camera feed, where individual frames can already be analyzed by the Vision framework and react to given observations. For example, if the user wants to record the camera feed and include the observations that were drawn onto the image.

Unfortunately, this would mean that at this point and during the "camera preview," there would be no active call yet. Of course, it would be possible to cover this use case with a separate view that only uses AVFoundation and the Vision framework, and then swap this view with the GetStream SDK logic once the user starts a call. However, this seems unnecessarily complicated to me.

For this reason, I am wondering if it is possible to implement a camera preview using the GetStream SDK, where the video filters that are normally applied during a call could already be applied.

I hope this explains my use case more clearly.

**Comment by andreasteich** [comment]
That's the best example I've found. This view looks to like it's possible to show the camera feed before joining or starting a call. I'm wondering how that's possible using the swift SDK.

![Bildschirmfoto 2024-08-22 um 10 18 41](https://github.com/user-attachments/assets/1c490eb9-b6f2-49fb-b52e-b847119967b6)

**Comment by andreasteich** [comment]
@ipavlidakis any news?

**Comment by ipavlidakis** [comment]
Hey @andreasteich 

Sorry for the delay. The page you sent me is also implemented on the iOS SDK under the name [LobbyView](https://github.com/GetStream/stream-video-swift/blob/0e8e550ae55ece37ac633957c5970a403083e377/Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift#L9). We also have some related documentation that can be find [here](https://getstream.io/video/docs/ios/ui-cookbook/lobby-preview/).

The way it works is by using the local track that is being created and render it using our [VideoRenderer](https://getstream.io/video/docs/ios/ui-components/video-renderer/) component.

Best regards,
Ilias

**Comment by andreasteich** [comment]
No problem, thank you very much for the information! I already tried to implement this kind of view, but couldn't get it to work cause of no active call that was present at this time. Maybe I did something wrong. I'll give the `LobbyView` another try. 

Do you have a link to a repository where I can find an example for that in iOS? I don't know how to get the `callSettings` initialized which get passed to the `LobbyView` via `@Binding`.

**Comment by ipavlidakis** [comment]
The `CallSettings` is a simple object that you can initialise from anywhere, so that shouldn't be a problem for now (the LobbyView only requires a binding to `CallSettings` as it changes them.).

> Do you have a link to a repository where I can find an example for that in iOS
The repository we are currently discussing on :). The [file](https://github.com/GetStream/stream-video-swift/blob/0e8e550ae55ece37ac633957c5970a403083e377/Sources/StreamVideoSwiftUI/CallingViews/PreJoiningView.swift#L9) I shared earlier, is the actual View we are using in our DemoApp (which you build by checking out this repo of course).

I'm going to close this ticket for now but please feel free to reopen if you keep facing issues or let us know on a new issue.

Best regards,
Ilias

**Comment by andreasteich** [comment]
Hey @ipavlidakis , 

sry I'm not able to reopen this issue, but I think I have to. Got it working to show a custom Lobby View and now I can preview the video footage as expected, thank you very much 🙏🏻 

My last question is: is it possible to set video filters for lobby preview as well? Currently I'm achieving this using `call.setVideoFilter(Filters.stream)` but I have no `call` object available yet. Is that possible via the `LobbyViewModel` as well?
