### ISSUE TITLE
Get reference to AVCaptureDevice

### ISSUE THREAD

**Issue by andreasteich** [GetStream/stream-video-swift#501]
## What are you trying to achieve?
I would need to get a reference to the initiated `AVCaptureDevice` to get the device and position information, but I can't find any information on that. Is it possible or does the SDK hides those relations completely to make it easier to use?

## If possible, how can you achieve this currently?
Maybe possible, but I'm not able to find the documentation.

**Comment by ipavlidakis** [comment]
Hi @andreasteich,

Thanks again for reaching out. Unfortunately we aren't exposing the AVCaptureDevice but we are exposing the device position which you can access from `Call.camera.direction`.

Would that help you cover your usecase?

Best regards,
Ilias

**Comment by andreasteich** [comment]
Thanks for responding @ipavlidakis , 

seems like I've already found a way to accomplish this situation. Don't need any further assistance here, because it was able to use default values to make it work.
